name: dent_is_pasien
description: Dent-IS Pasien

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http:
  dio:
  path_provider: ^0.4.0
  cookie_jar: ^1.0.0
  url_launcher: ^4.0.0
  webview_flutter: ^0.2.0
  image_picker: ^0.4.0
  fluttertoast: ^3.0.3

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/button-dokter.png
    - assets/button-pasien.png
    - assets/button-manajer.png
    - assets/button-instansi.png
    - assets/logo.png
    - assets/gradient-button.png
    - assets/gradient-footer.png
    - assets/users.png
    - assets/appointments.png
    - assets/appointment.png
    - assets/faqs.png
    - assets/kuisioner.png
    - assets/plus-circle.png
    - assets/line.png
    - assets/odontogram/gigi4kecil.png
    - assets/odontogram/gigi5kecil.png
    - assets/odontogram/gigi5kecilselected.png 
    - assets/odontogram/gigi4kecilselected.png 
    - assets/detailGigi/gigi5/bg.png
    - assets/detailGigi/gigi5/d.png
    - assets/detailGigi/gigi5/l.png
    - assets/detailGigi/gigi5/m.png
    - assets/detailGigi/gigi5/o.png
    - assets/detailGigi/gigi5/v.png
    - assets/detailGigi/gigi4/bg.png
    - assets/detailGigi/gigi4/d.png
    - assets/detailGigi/gigi4/l.png
    - assets/detailGigi/gigi4/m.png 
    - assets/detailGigi/gigi4/v.png
    - assets/tabs/status.png
    - assets/tabs/status-selected.png
    - assets/tabs/ohis.png
    - assets/tabs/ohis-selected.png
    - assets/profile-picture.png
    - assets/error.png
    - assets/wallpapers/wallpaper1.png 
    - assets/wallpapers/wallpaper2.png
    - assets/wallpapers/wallpaper3.png
    - assets/folder.png
    - assets/news.png
    - assets/instansi.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
